# Site settings
title: kdmsnr.com
email: kdmsnr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kdmsnr.com" # the base hostname & protocol for your site
twitter_username: kdmsnr
github_username:  kdmsnr
timezone: Asia/Tokyo

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [autolink,strikethrough,footnotes]

gems:
  - jekyll-sitemap
  - jemoji

# Amazon plugin
amazon_access_key_id: 'your access key id'
amazon_secret_key:    'your secret key'
amazon_associate_tag: '99-22'
amazon_cache:         true
amazon_cache_dir:     '.amazon-cache'      # default '.amazon-cache'
amazon_country:       'jp'                 # default 'en'
amazon_locale:        'ja'                 # default 'en'
