# Site settings
title: kdmsnr.com
email: kdmsnr@gmail.com
description: "角征典's Web Site"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kdmsnr.com" # the base hostname & protocol for your site
twitter_username: kdmsnr
github_username:  kdmsnr
timezone: Asia/Tokyo

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - vendor

defaults:
  -
    scope:
      path:            "/files/*"
    values:
      sitemap:         false
